### ISSUE TITLE
Please support more standard less keybindings

### ISSUE THREAD

**Issue by hupfdule** [noborus/ov#28]
It would ease the use of ov if it would provide all the same keybindings as less. Currently only some of its keybindungs are supported. Currently unsupported are e.g. `j` and `k` for scrolling down and up or `space` and `ctrl-f` for pagewise scrolling.

**Comment by noborus** [comment]
Thank you very much.
I'm thinking of adding standard keybindings, but I'd also like to have some patterns of configuration file (ov.yaml) templates(copy to ~ /.ov.yaml.).
If you send me an ov.yaml that I think is standard, I'll add it to the repository.
If you want to add your point to ov.yaml:

```
--- ov.yaml	2020-10-21 18:36:31.137016303 +0900
+++ ov.yaml.less	2020-10-21 18:50:31.726422973 +0900
@@ -28,41 +28,45 @@
         - "ctrl+l"
     help:
         - "h"
         - "ctrl+alt+c"
     logdoc:
         - "ctrl+alt+e"
     down:
         - "Enter"
         - "Down"
         - "ctrl+N"
+        - "j"
     up:
         - "Up"
         - "ctrl+p"
+        - "k"
     top:
         - "Home"
     bottom:
         - "End"
     left:
         - "left"
     right:
         - "right"
     half_left:
         - "ctrl+left"
     half_right:
         - "ctrl+right"
     page_up:
         - "PageUp"
         - "ctrl+b"
     page_down:
         - "PageDown"
         - "ctrl+v"
+        - "ctrl+f"
+        - "space"
     page_half_up:
         - "ctrl+u"
     page_half_down:
         - "ctrl+d"
     mark:
         - "m"
     next_mark:
         - ">"
     previous_mark:
         - "<"
```
