### ISSUE TITLE
Explain how to set both the background and foreground color for elements

### ISSUE THREAD

**Issue by nkh** [noborus/ov#427]
I tried multiple combinations in the config.yaml file without success.

When using --column-rainbow setting both background and foreground is a necessity.

**Comment by noborus** [comment]
sorry.
What about this example?

```yaml
StyleColumnRainbow:
    - Foreground: "white"
      Background: "red"
    - Foreground: "crimson"
      Underline: true
    - Foreground: "#ff7f00"
      Background: "blue"
      Bold: true
    - Foreground: "lightsalmon"
      Italic: true
    - Foreground: "lime"
      Dim: true
    - Foreground: "blue"
    - Foreground: "yellowgreen"
```
