### ISSUE TITLE
Double line numbers under bat

### ISSUE THREAD

**Issue by gcflymoto** [noborus/ov#735]
Hi, thank you for this excellent and all-powerful pager. I am ramping up on using it and tried this kind of config.yaml
```
General:
  TabWidth: 4
  Header: 0
  AlternateRows: false
  ColumnMode: false
  LineNumMode: true # enable line numbers by default
  WrapMode: false
  ColumnDelimiter: ","
  MarkStyleWidth: 1

Mode:
  bat:
    LineNumMode: false # Attempt to disable line numbers under bat
```

Then, I tried to pick this mode with --view-mode bat

```ov --help | env BAT_PAGER='ov -F -H3 --view-mode bat' bat -l help```

But getting double line numbers, ones from `ov` and ones from `bat`
