### ISSUE TITLE
`OverStrike` and `OverLine` Styles Not Applied in Mode-Specific Configuration

### ISSUE THREAD

**Issue by liblaf** [noborus/ov#770]
Thank you for creating and maintaining `ov`! It's been incredibly useful for viewing man pages with color. I've encountered an issue with styling `OverStrike` and `OverLine` in the mode-specific configuration and wanted to report it.

### Description

When defining `OverStrike` and `OverLine` styles under `Mode.man.Style` in the YAML config, the styles are not applied as expected. However, switching to the legacy top-level `StyleOverStrike` and `StyleOverLine` keys works correctly.

### Config Examples

**New Format (Not Working):**
```yaml
Mode:
  man:
    SectionDelimiter: ^[^\s]
    Style:
      OverStrike:
        Foreground: aqua
        Bold: true
      OverLine:
        Foreground: red
        Underline: true
```

![Image](https://github.com/user-attachments/assets/6a0f5b81-cf5e-4a0d-9c8f-370b7d215715)

**Legacy Format (Working):**
```yaml
Mode:
  man:
    SectionDelimiter: ^[^\s]
StyleOverStrike:
  Foreground: aqua
  Bold: true
StyleOverLine:
  Foreground: red
  Underline: true
```

![Image](https://github.com/user-attachments/assets/b0c7c472-0d90-4993-934f-c0579a1e9abe)

### Expected vs. Observed Behavior
- **Expected:** Styles defined under `Mode.man.Style` should apply.
- **Observed:** Only the legacy top-level style definitions work.

### Environment
- `ov` Version: 0.40.1 rev:b491ebc
- OS: Linux

### Notes

This might indicate a parsing issue with nested style definitions in mode configurations or a documentation mismatch. Let me know if further details are needed!

Thank you for your time and effort! 🙏
