### ISSUE TITLE
Feature request: allow setting more options for a view mode

### ISSUE THREAD

**Issue by visrosa** [noborus/ov#791]
I was trying to create a view mode for the output of `inxi` and noticed that some options I want can only be set via commandline or interactively.

Specifically , `--multi-color` and `--hide-other-section`. 

It would be nice to be able to be able to customize ov's behavior more completely in the config file and in the view modes.

**Comment by noborus** [comment]
Thank you for the issue.

I'm sorry, this wasn't written in the `README.md` document.
Actually, you can set it in view mode as well.
You can write it like this.

```yaml
Mode:
  markdown:
    SectionDelimiter: "^#"
    WrapMode: true
    MultiColorWords:
      - "ov"
      - "support"
      - "multi"
    HideOtherSection: true
    Style:
      SectionLine:
        Background: "blue"
```

I'll edit README.md later.
